version: '2'

volumes:
  nextcloud_db:
  nextcloud_:
  nextcloud_data:
  nextcloud_apps:
  nextcloud_config:
  nextcloud_haproxy:
  
services:
  db:
    image: localhost:5000/mariadb:11.1.3
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12qw34er
      - MYSQL_PASSWORD=12qw34er
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: localhost:5000/nextcloud:27.1.3-apache
    restart: always
    links:
      - db
    volumes:
      - nextcloud_:/var/www/html
      - nextcloud_data:/var/www/html/data
      - nextcloud_apps:/var/www/html/custom_apps
      - nextcloud_config:/var/www/html/config
    environment:
      - MYSQL_PASSWORD=12qw34er
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=ncadmin
      - NEXTCLOUD_ADMIN_PASSWORD=12qw34er
      - PHP_UPLOAD_LIMIT=12G
      - NEXTCLOUD_TRUSTED_DOMAINS=files.mydomain.com
      - OVERWRITEHOST=files.mydomain.com
      - OVERWRITEPROTOCOL=https

  haproxy:
    image: localhost:5000/haproxy:2.8.4
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - app
    volumes:
      - nextcloud_haproxy:/usr/local/etc/haproxy
